bot_name:
slack_api_token:
github_api_token:

default_channel: general
default_times:
  - hour: 24
    minute: 54

reminders:
  - repo: jjshoe/slackbot-pr-reminder
    channel: general
    times: 
      - hour: 16
        minute:  56 
      - hour: 16
        minute:  58
